version: '3.8'

services:
  # Flask应用
  app:
    build: .
    container_name: ai-memory-app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-secret-key-change-in-production}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_ENV=development
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
      - ./templates:/app/templates
    depends_on:
      - redis
    networks:
      - ai-memory-network
    restart: unless-stopped

  # Redis用于缓存和异步任务队列
  redis:
    image: redis:7-alpine
    container_name: ai-memory-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ai-memory-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  ai-memory-network:
    driver: bridge

volumes:
  redis-data:
